[phases.setup]
nixPkgs = ["...", "python311", "postgresql"]

[phases.install]
cmds = [
  "cd clean-backend && python -m pip install --upgrade pip",
  "cd clean-backend && pip install -r requirements.txt"
]

[start]
cmd = "cd clean-backend && python run.py"